#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh


bspc monitor HDMI-1 -d VI VII VIII IX X
bspc monitor eDP-1 -d I II III IV V  

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


xsetroot -cursor_name left_ptr &
picom -f & 
nitrogen --restore
